package org.servialtura.contabilad.base.model;
// default package
// Generated 30-dic-2016 19:16:06 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.servialtura.contabilidad.base.model.Material;
import org.servialtura.contabilidad.base.model.Presupuesto;

/**
 * MaterialesPresupuesto generated by hbm2java
 */
@Embeddable
public class MaterialesPresupuestoId implements java.io.Serializable {


	/**
	 * 
	 */
	private static final long serialVersionUID = -5534965263764828287L;
	private Presupuesto presupuesto;
	private Material material;

	public MaterialesPresupuestoId() {
	}

	public MaterialesPresupuestoId(Presupuesto presupuesto, Material material) {
		this.presupuesto = presupuesto;
		this.material = material;
	}

	@Column(name = "idPresupuesto", nullable = false)
	public Presupuesto getPresupuesto() {
		return this.presupuesto;
	}

	public void setPresupuesto(Presupuesto presupuesto) {
		this.presupuesto = presupuesto;
	}

	@Column(name = "idMaterial", nullable = false)
	public Material getMaterial() {
		return this.material;
	}

	public void setMaterial(Material material) {
		this.material = material;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((material == null) ? 0 : material.hashCode());
		result = prime * result + ((presupuesto == null) ? 0 : presupuesto.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (!(obj instanceof MaterialesPresupuestoId))
			return false;
		MaterialesPresupuestoId other = (MaterialesPresupuestoId) obj;
		if (material == null) {
			if (other.material != null)
				return false;
		} else if (!material.equals(other.getMaterial()))
			return false;
		if (presupuesto == null) {
			if (other.presupuesto != null)
				return false;
		} else if (!presupuesto.equals(other.getPresupuesto()))
			return false;
		return true;
	}


}
