package org.servialtura.contabilidad.base.model;
// default package
// Generated 08-ene-2017 17:44:23 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Album generated by hbm2java
 */
@Entity
@Table(name = "ALBUM", catalog = "SERVIALTURA")
public class Album implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -9157661204297951894L;
	private Integer idAlbum;
	private Obra obra;
	private String nombreAlbum;

	public Album() {
	}

	public Album(Obra obra, String nombreAlbum) {
		this.obra = obra;
		this.nombreAlbum = nombreAlbum;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idAlbum", unique = true, nullable = false)
	public Integer getIdAlbum() {
		return this.idAlbum;
	}

	public void setIdAlbum(Integer idAlbum) {
		this.idAlbum = idAlbum;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idObra")
	public Obra getObra() {
		return this.obra;
	}

	public void setObra(Obra obra) {
		this.obra = obra;
	}

	@Column(name = "nombre_album")
	public String getNombreAlbum() {
		return this.nombreAlbum;
	}

	public void setNombreAlbum(String nombreAlbum) {
		this.nombreAlbum = nombreAlbum;
	}

}
