package org.servialtura.contabilidad.base.model;
// default package
// Generated 18-dic-2016 18:36:13 by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CategoriaServicio generated by hbm2java
 */
@Entity
@Table(name = "CATEGORIA_SERVICIO", catalog = "SERVIALTURA")
public class CategoriaServicio implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6340768574606431128L;
	private Integer idCategoriaServicio;
	private String nombreCategoria;
	private List<Servicio> servicios = new ArrayList<Servicio>();

	public CategoriaServicio() {
	}



	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idCategoriaServicio", unique = true, nullable = false)
	public Integer getIdCategoriaServicio() {
		return this.idCategoriaServicio;
	}

	public void setIdCategoriaServicio(Integer idCategoriaServicio) {
		this.idCategoriaServicio = idCategoriaServicio;
	}

	@Column(name = "nombreCategoria")
	public String getNombreCategoria() {
		return this.nombreCategoria;
	}

	public void setNombreCategoria(String nombreCategoria) {
		this.nombreCategoria = nombreCategoria;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categoriaServicio")
	public List<Servicio> getServicios() {
		return this.servicios;
	}

	public void setServicios(List<Servicio> servicios) {
		this.servicios = servicios;
	}

}
