package org.servialtura.contabilidad.base.model;
// default package
// Generated 18-dic-2016 18:36:13 by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CategoriaMaterial generated by hbm2java
 */
@Entity
@Table(name = "CATEGORIA_MATERIAL", catalog = "SERVIALTURA")
public class CategoriaMaterial implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6340768574606431128L;
	private Integer idCategoriaMaterial;
	private String nombreCategoria;

	public CategoriaMaterial() {
	}



	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idCategoriaMaterial", unique = true, nullable = false)
	public Integer getIdCategoriaMaterial() {
		return this.idCategoriaMaterial;
	}

	public void setIdCategoriaMaterial(Integer idCategoriaMaterial) {
		this.idCategoriaMaterial = idCategoriaMaterial;
	}

	@Column(name = "nombreCategoria")
	public String getNombreCategoria() {
		return this.nombreCategoria;
	}

	public void setNombreCategoria(String nombreCategoria) {
		this.nombreCategoria = nombreCategoria;
	}



	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idCategoriaMaterial == null) ? 0 : idCategoriaMaterial.hashCode());
		return result;
	}



	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (!(obj instanceof CategoriaMaterial))
			return false;
		CategoriaMaterial other = (CategoriaMaterial) obj;
		if (idCategoriaMaterial == null) {
			if (other.getIdCategoriaMaterial() != null)
				return false;
		} else if (!idCategoriaMaterial.equals(other.getIdCategoriaMaterial()))
			return false;
		return true;
	}

}
