package org.servialtura.contabilidad.base.model;
// default package
// Generated 01-oct-2016 18:39:37 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CategoriaMaterial generated by hbm2java
 */
@Entity
@Table(name = "CATEGORIA_MATERIAL", catalog = "SERVIALTURA")
public class CategoriaMaterial implements java.io.Serializable {

	private Integer idCategoriaMaterial;
	private String nombreCategoria;
	private Set<Material> materials = new HashSet<Material>(0);

	public CategoriaMaterial() {
	}

	public CategoriaMaterial(String nombreCategoria, Set<Material> materials) {
		this.nombreCategoria = nombreCategoria;
		this.materials = materials;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idCategoriaMaterial", unique = true, nullable = false)
	public Integer getIdCategoriaMaterial() {
		return this.idCategoriaMaterial;
	}

	public void setIdCategoriaMaterial(Integer idCategoriaMaterial) {
		this.idCategoriaMaterial = idCategoriaMaterial;
	}

	@Column(name = "nombre_categoria", length = 45)
	public String getNombreCategoria() {
		return this.nombreCategoria;
	}

	public void setNombreCategoria(String nombreCategoria) {
		this.nombreCategoria = nombreCategoria;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categoriaMaterial")
	public Set<Material> getMaterials() {
		return this.materials;
	}

	public void setMaterials(Set<Material> materials) {
		this.materials = materials;
	}

}
