package org.servialtura.contabilidad.base.model;
// default package
// Generated 01-oct-2016 18:39:37 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name = "CLIENTE", catalog = "SERVIALTURA")
public class Cliente implements java.io.Serializable {

	private Integer idCliente;
	private String nombreCliente;
	private String nifCliente;
	private String emailCliente;
	private String telefonoCliente;
	private String direccionCliente;

	public Cliente() {
	}

	public Cliente(String nombreCliente, String nifCliente, String emailCliente, String telefonoCliente,
			String direccionCliente) {
		this.nombreCliente = nombreCliente;
		this.nifCliente = nifCliente;
		this.emailCliente = emailCliente;
		this.telefonoCliente = telefonoCliente;
		this.direccionCliente = direccionCliente;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idCliente", unique = true, nullable = false)
	public Integer getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(Integer idCliente) {
		this.idCliente = idCliente;
	}

	@Column(name = "nombre_cliente", length = 45)
	public String getNombreCliente() {
		return this.nombreCliente;
	}

	public void setNombreCliente(String nombreCliente) {
		this.nombreCliente = nombreCliente;
	}

	@Column(name = "nif_cliente", length = 45)
	public String getNifCliente() {
		return this.nifCliente;
	}

	public void setNifCliente(String nifCliente) {
		this.nifCliente = nifCliente;
	}

	@Column(name = "email_cliente", length = 30)
	public String getEmailCliente() {
		return this.emailCliente;
	}

	public void setEmailCliente(String emailCliente) {
		this.emailCliente = emailCliente;
	}

	@Column(name = "telefono_cliente", length = 20)
	public String getTelefonoCliente() {
		return this.telefonoCliente;
	}

	public void setTelefonoCliente(String telefonoCliente) {
		this.telefonoCliente = telefonoCliente;
	}

	@Column(name = "direccion_cliente", length = 150)
	public String getDireccionCliente() {
		return this.direccionCliente;
	}

	public void setDireccionCliente(String direccionCliente) {
		this.direccionCliente = direccionCliente;
	}

}
