package org.servialtura.contabilidad.base.model;
// default package
// Generated 25-dic-2016 12:18:51 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Contacto generated by hbm2java
 */
@Entity
@Table(name = "CONTACTO", catalog = "SERVIALTURA")
public class Contacto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4184179474880621953L;
	private Integer idContacto;
	private Empresa empresa;
	private String nombreContacto;
	private String emailContacto;
	private String direccionContacto;
	private String telefonoContacto;

	public Contacto() {
	}

	public Contacto(String nombreContacto) {
		this.nombreContacto = nombreContacto;
	}

	public Contacto(Empresa empresa, String nombreContacto, String emailContacto, String direccionContacto,
			String telefonoContacto) {
		this.empresa = empresa;
		this.nombreContacto = nombreContacto;
		this.emailContacto = emailContacto;
		this.direccionContacto = direccionContacto;
		this.telefonoContacto = telefonoContacto;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idContacto", unique = true, nullable = false)
	public Integer getIdContacto() {
		return this.idContacto;
	}

	public void setIdContacto(Integer idContacto) {
		this.idContacto = idContacto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idEmpresa")
	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	@Column(name = "nombre_contacto", nullable = false)
	public String getNombreContacto() {
		return this.nombreContacto;
	}

	public void setNombreContacto(String nombreContacto) {
		this.nombreContacto = nombreContacto;
	}

	@Column(name = "email_contacto")
	public String getEmailContacto() {
		return this.emailContacto;
	}

	public void setEmailContacto(String emailContacto) {
		this.emailContacto = emailContacto;
	}

	@Column(name = "direccion_contacto")
	public String getDireccionContacto() {
		return this.direccionContacto;
	}

	public void setDireccionContacto(String direccionContacto) {
		this.direccionContacto = direccionContacto;
	}

	@Column(name = "telefono_contacto")
	public String getTelefonoContacto() {
		return this.telefonoContacto;
	}

	public void setTelefonoContacto(String telefonoContacto) {
		this.telefonoContacto = telefonoContacto;
	}

}
