package org.servialtura.contabilidad.base.model;
// default package
// Generated 01-oct-2016 18:39:37 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Factura generated by hbm2java
 */
@Entity
@Table(name = "FACTURA", catalog = "SERVIALTURA")
public class Factura implements java.io.Serializable {

	private Integer idFactura;
	private Presupuesto presupuesto;
	private Date fechaEnviada;
	private Date fechaGirada;
	private Date fechaCobrada;
	private Integer idCliente;

	public Factura() {
	}

	public Factura(Presupuesto presupuesto, Date fechaEnviada, Date fechaGirada, Date fechaCobrada, Integer idCliente) {
		this.presupuesto = presupuesto;
		this.fechaEnviada = fechaEnviada;
		this.fechaGirada = fechaGirada;
		this.fechaCobrada = fechaCobrada;
		this.idCliente = idCliente;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idFactura", unique = true, nullable = false)
	public Integer getIdFactura() {
		return this.idFactura;
	}

	public void setIdFactura(Integer idFactura) {
		this.idFactura = idFactura;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_presupuesto")
	public Presupuesto getPresupuesto() {
		return this.presupuesto;
	}

	public void setPresupuesto(Presupuesto presupuesto) {
		this.presupuesto = presupuesto;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_enviada", length = 19)
	public Date getFechaEnviada() {
		return this.fechaEnviada;
	}

	public void setFechaEnviada(Date fechaEnviada) {
		this.fechaEnviada = fechaEnviada;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_girada", length = 19)
	public Date getFechaGirada() {
		return this.fechaGirada;
	}

	public void setFechaGirada(Date fechaGirada) {
		this.fechaGirada = fechaGirada;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_cobrada", length = 19)
	public Date getFechaCobrada() {
		return this.fechaCobrada;
	}

	public void setFechaCobrada(Date fechaCobrada) {
		this.fechaCobrada = fechaCobrada;
	}

	@Column(name = "idCliente")
	public Integer getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(Integer idCliente) {
		this.idCliente = idCliente;
	}

}
