package org.servialtura.contabilidad.base.model;
// default package
// Generated 08-ene-2017 17:17:12 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * FileMeta generated by hbm2java
 */
@Entity
@Table(name = "FILE_META", catalog = "SERVIALTURA")
public class FileMeta implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3149477569012716011L;
	private Integer idFile;
	private FileStore fileStore;
	private String fileName;
	private String fileDescription;
	private String contentType;
	private Long fileSize;
	private Date uploadDate;

	public FileMeta() {
	}

	public FileMeta(FileStore fileStore) {
		this.fileStore = fileStore;
	}


	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "fileStore"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "ID_FILE", unique = true, nullable = false)
	public Integer getIdFile() {
		return this.idFile;
	}

	public void setIdFile(Integer idFile) {
		this.idFile = idFile;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public FileStore getFileStore() {
		return this.fileStore;
	}

	public void setFileStore(FileStore fileStore) {
		this.fileStore = fileStore;
	}

	@Column(name = "FILE_NAME")
	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@Column(name = "FILE_DESCRIPTION", length = 16777215)
	public String getFileDescription() {
		return this.fileDescription;
	}

	public void setFileDescription(String fileDescription) {
		this.fileDescription = fileDescription;
	}

	@Column(name = "CONTENT_TYPE")
	public String getContentType() {
		return this.contentType;
	}

	public void setContentType(String contentType) {
		this.contentType = contentType;
	}

	@Column(name = "FILE_SIZE")
	public Long getFileSize() {
		return this.fileSize;
	}

	public void setFileSize(Long fileSize) {
		this.fileSize = fileSize;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPLOAD_DATE", length = 19)
	public Date getUploadDate() {
		return this.uploadDate;
	}

	public void setUploadDate(Date uploadDate) {
		this.uploadDate = uploadDate;
	}

}
