package org.servialtura.contabilidad.base.model;
// default package
// Generated 18-oct-2016 19:34:49 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LineaPartida generated by hbm2java
 */
@Entity
@Table(name = "LINEA_PARTIDA", catalog = "SERVIALTURA")
public class LineaPartida implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4072534295574536963L;
	private Long idLinea;
	private Partida partida;
	private String descripcionLineaPresupuesto;

	public LineaPartida() {
	}

	public LineaPartida(Partida partida, String descripcionLineaPresupuesto) {
		this.partida = partida;
		this.descripcionLineaPresupuesto = descripcionLineaPresupuesto;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idLinea", unique = true, nullable = false)
	public Long getIdLinea() {
		return this.idLinea;
	}

	public void setIdLinea(Long idLinea) {
		this.idLinea = idLinea;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_partida")
	public Partida getPartida() {
		return this.partida;
	}

	public void setPartida(Partida partida) {
		this.partida = partida;
	}

	@Column(name = "descripcion_linea_presupuesto", length = 100)
	public String getDescripcionLineaPresupuesto() {
		return this.descripcionLineaPresupuesto;
	}

	public void setDescripcionLineaPresupuesto(String descripcionLineaPresupuesto) {
		this.descripcionLineaPresupuesto = descripcionLineaPresupuesto;
	}

}
