package org.servialtura.contabilidad.base.model;
// default package
// Generated 01-oct-2016 18:39:37 by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LineaPresupuesto generated by hbm2java
 */
@Entity
@Table(name = "LINEA_PRESUPUESTO", catalog = "SERVIALTURA")
public class LineaPresupuesto implements java.io.Serializable {

	private static final long serialVersionUID = 8781712730942521902L;
	private Long idLinea;
	private String descripcionLineaPresupuesto;
	private Presupuesto presupuesto;

	public LineaPresupuesto() {
	}

	public LineaPresupuesto(String descripcionLineaPresupuesto) {
		this.descripcionLineaPresupuesto = descripcionLineaPresupuesto;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idLinea", unique = true, nullable = false)
	public Long getIdLinea() {
		return this.idLinea;
	}

	public void setIdLinea(Long idLinea) {
		this.idLinea = idLinea;
	}

	@Column(name = "descripcion_linea_presupuesto", length = 100)
	public String getDescripcionLineaPresupuesto() {
		return this.descripcionLineaPresupuesto;
	}

	public void setDescripcionLineaPresupuesto(String descripcionLineaPresupuesto) {
		this.descripcionLineaPresupuesto = descripcionLineaPresupuesto;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idLinea == null) ? 0 : idLinea.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (!(obj instanceof LineaPresupuesto))
			return false;
		LineaPresupuesto other = (LineaPresupuesto) obj;
		if (idLinea == null) {
			if (other.getIdLinea() != null)
				return false;
		} else if (!idLinea.equals(other.getIdLinea()))
			return false;
		return true;
	}
	
	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	public Presupuesto getPresupuesto() {
		return presupuesto;
	}

	public void setPresupuesto(Presupuesto presupuesto) {
		this.presupuesto = presupuesto;
	}
	
	

}
