package org.servialtura.contabilidad.base.model;
// default package
// Generated 01-oct-2016 18:39:37 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LineaPresupuesto generated by hbm2java
 */
@Entity
@Table(name = "LINEA_PRESUPUESTO", catalog = "SERVIALTURA")
public class LineaPresupuesto implements java.io.Serializable {

	private Long idLinea;
	private String descripcionLineaPresupuesto;

	public LineaPresupuesto() {
	}

	public LineaPresupuesto(String descripcionLineaPresupuesto) {
		this.descripcionLineaPresupuesto = descripcionLineaPresupuesto;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idLinea", unique = true, nullable = false)
	public Long getIdLinea() {
		return this.idLinea;
	}

	public void setIdLinea(Long idLinea) {
		this.idLinea = idLinea;
	}

	@Column(name = "descripcion_linea_presupuesto", length = 100)
	public String getDescripcionLineaPresupuesto() {
		return this.descripcionLineaPresupuesto;
	}

	public void setDescripcionLineaPresupuesto(String descripcionLineaPresupuesto) {
		this.descripcionLineaPresupuesto = descripcionLineaPresupuesto;
	}

}
