package org.servialtura.contabilidad.base.model;
// default package
// Generated 01-oct-2016 18:39:37 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Material generated by hbm2java
 */
@Entity
@Table(name = "MATERIAL", catalog = "SERVIALTURA")
public class Material implements java.io.Serializable {

	private Integer idMaterial;
	private CategoriaMaterial categoriaMaterial;
	private String descripcionMaterial;
	private Float precioUnidad;

	public Material() {
	}

	public Material(CategoriaMaterial categoriaMaterial, String descripcionMaterial, Float precioUnidad) {
		this.categoriaMaterial = categoriaMaterial;
		this.descripcionMaterial = descripcionMaterial;
		this.precioUnidad = precioUnidad;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idMaterial", unique = true, nullable = false)
	public Integer getIdMaterial() {
		return this.idMaterial;
	}

	public void setIdMaterial(Integer idMaterial) {
		this.idMaterial = idMaterial;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idCategoriaMaterial")
	public CategoriaMaterial getCategoriaMaterial() {
		return this.categoriaMaterial;
	}

	public void setCategoriaMaterial(CategoriaMaterial categoriaMaterial) {
		this.categoriaMaterial = categoriaMaterial;
	}

	@Column(name = "descripcion_material", length = 45)
	public String getDescripcionMaterial() {
		return this.descripcionMaterial;
	}

	public void setDescripcionMaterial(String descripcionMaterial) {
		this.descripcionMaterial = descripcionMaterial;
	}

	@Column(name = "precio_unidad", precision = 12, scale = 0)
	public Float getPrecioUnidad() {
		return this.precioUnidad;
	}

	public void setPrecioUnidad(Float precioUnidad) {
		this.precioUnidad = precioUnidad;
	}

}
