package org.servialtura.contabilidad.base.model;
// default package
// Generated 30-dic-2016 19:16:06 by Hibernate Tools 4.3.1.Final

import javax.persistence.AssociationOverride;
import javax.persistence.AssociationOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.servialtura.contabilad.base.model.MaterialesPresupuestoId;

/**
 * MaterialesPresupuesto generated by hbm2java
 */
@Entity
@Table(name = "MATERIALES_PRESUPUESTO", catalog = "SERVIALTURA")
@AssociationOverrides({
	@AssociationOverride(name = "id.material",
		joinColumns = @JoinColumn(name = "idMaterial")),
	@AssociationOverride(name = "id.presupuesto",
		joinColumns = @JoinColumn(name = "idPresupuesto")) })
public class MaterialesPresupuesto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3036925999478037892L;
	private MaterialesPresupuestoId id = new MaterialesPresupuestoId();
	private Float cantidad;
	public MaterialesPresupuesto() {
	}

	public MaterialesPresupuesto(MaterialesPresupuestoId id) {
		this.id = id;

	}

	public MaterialesPresupuesto(MaterialesPresupuestoId id,
			Float cantidad) {
		this.id = id;

		this.cantidad = cantidad;
	}

	@EmbeddedId
	public MaterialesPresupuestoId getId() {
		return this.id;
	}

	public void setId(MaterialesPresupuestoId id) {
		this.id = id;
	}


	@Column(name = "cantidad", precision = 12, scale = 0)
	public Float getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Float cantidad) {
		this.cantidad = cantidad;
	}


	@Transient
	public Material getMaterial() {
		return getId().getMaterial();
	}

	public void setMaterial(Material material) {
		this.getId().setMaterial(material);
	}


	@Transient
	public Presupuesto getPresupuesto() {
		return getId().getPresupuesto();
	}

	public void setPresupuesto(Presupuesto presupuesto) {
			getId().setPresupuesto( presupuesto);
	}

}
