package org.servialtura.contabilidad.base.model;
// default package
// Generated 30-dic-2016 19:16:06 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.servialtura.contabilad.base.model.MaterialesPresupuestoId;

/**
 * MaterialesPresupuesto generated by hbm2java
 */
@Entity
@Table(name = "MATERIALES_PRESUPUESTO", catalog = "SERVIALTURA")
public class MaterialesPresupuesto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3036925999478037892L;
	private MaterialesPresupuestoId id;
	private Float cantidad;
	private Presupuesto presupuesto;
	private Material material;

	public MaterialesPresupuesto() {
	}

	public MaterialesPresupuesto(MaterialesPresupuestoId id) {
		this.id = id;

	}

	public MaterialesPresupuesto(MaterialesPresupuestoId id,
			Float cantidad) {
		this.id = id;

		this.cantidad = cantidad;
	}

	@EmbeddedId
	public MaterialesPresupuestoId getId() {
		return this.id;
	}

	public void setId(MaterialesPresupuestoId id) {
		this.id = id;
	}


	@Column(name = "cantidad", precision = 12, scale = 0)
	public Float getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Float cantidad) {
		this.cantidad = cantidad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idMaterial", nullable = false, insertable = false, updatable = false)
	public Material getMaterial() {
		return this.material;
	}

	public void setMaterial(Material material) {
		this.material = material;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idPresupuesto", nullable = false, insertable = false, updatable = false)
	public Presupuesto getPresupuesto() {
		return this.presupuesto;
	}

	public void setPresupuesto(Presupuesto presupuesto) {
		this.presupuesto = presupuesto;
	}

}
