package org.servialtura.contabilidad.base.model;
// default package
// Generated 08-ene-2017 17:38:18 by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Obra generated by hbm2java
 */
@Entity
@Table(name = "OBRA", catalog = "SERVIALTURA")
public class Obra implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5421159626013113318L;
	private Integer idObra;
	private Presupuesto presupuesto;
	private String estadoObra;
	private Date fechaInicio;
	private Date fechaFin;
	private Date fechaEstimadaInicio;
	private Date fechaEstimadaFin;
	private Set<Album> albums = new HashSet<Album>(0);

	public Obra() {
	}



	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_OBRA", unique = true, nullable = false)
	public Integer getIdObra() {
		return this.idObra;
	}

	public void setIdObra(Integer idObra) {
		this.idObra = idObra;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_presupuesto")
	public Presupuesto getPresupuesto() {
		return this.presupuesto;
	}

	public void setPresupuesto(Presupuesto presupuesto) {
		this.presupuesto = presupuesto;
	}

	@Column(name = "ESTADO_OBRA")
	public String getEstadoObra() {
		return this.estadoObra;
	}

	public void setEstadoObra(String estadoObra) {
		this.estadoObra = estadoObra;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHA_INICIO", length = 19)
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHA_FIN", length = 19)
	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHA_ESTIMADA_INICIO", length = 19)
	public Date getFechaEstimadaInicio() {
		return this.fechaEstimadaInicio;
	}

	public void setFechaEstimadaInicio(Date fechaEstimadaInicio) {
		this.fechaEstimadaInicio = fechaEstimadaInicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHA_ESTIMADA_FIN", length = 19)
	public Date getFechaEstimadaFin() {
		return this.fechaEstimadaFin;
	}

	public void setFechaEstimadaFin(Date fechaEstimadaFin) {
		this.fechaEstimadaFin = fechaEstimadaFin;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "obra")
	public Set<Album> getAlbums() {
		return this.albums;
	}

	public void setAlbums(Set<Album> albums) {
		this.albums = albums;
	}

}
