package org.servialtura.contabilidad.base.model;
// default package
// Generated 01-oct-2016 18:39:37 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Pago generated by hbm2java
 */
@Entity
@Table(name = "PAGO", catalog = "SERVIALTURA")
public class Pago implements java.io.Serializable {

	private Integer idPago;
	private Empleado empleado;
	private String descripcionPago;
	private String numeroFactura;
	private String importe;

	public Pago() {
	}

	public Pago(Empleado empleado, String descripcionPago, String numeroFactura, String importe) {
		this.empleado = empleado;
		this.descripcionPago = descripcionPago;
		this.numeroFactura = numeroFactura;
		this.importe = importe;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idPago", unique = true, nullable = false)
	public Integer getIdPago() {
		return this.idPago;
	}

	public void setIdPago(Integer idPago) {
		this.idPago = idPago;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idEmpleado")
	public Empleado getEmpleado() {
		return this.empleado;
	}

	public void setEmpleado(Empleado empleado) {
		this.empleado = empleado;
	}

	@Column(name = "descripcion_pago", length = 100)
	public String getDescripcionPago() {
		return this.descripcionPago;
	}

	public void setDescripcionPago(String descripcionPago) {
		this.descripcionPago = descripcionPago;
	}

	@Column(name = "numero_factura", length = 100)
	public String getNumeroFactura() {
		return this.numeroFactura;
	}

	public void setNumeroFactura(String numeroFactura) {
		this.numeroFactura = numeroFactura;
	}

	@Column(name = "importe", length = 45)
	public String getImporte() {
		return this.importe;
	}

	public void setImporte(String importe) {
		this.importe = importe;
	}

}
