package org.servialtura.contabilidad.base.model;
// default package
// Generated 18-dic-2016 13:04:56 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.servialtura.contabilidad.base.enums.EstadoPresupuestoEnum;

/**
 * Partida generated by hbm2java
 */
@Entity
@Table(name = "PARTIDA", catalog = "SERVIALTURA")
public class Partida implements java.io.Serializable {

	private static final long serialVersionUID = 6052820672470577748L;
	private Integer idPartida;
	private Presupuesto presupuesto;
	private EstadoPresupuestoEnum estadoPartida;
	private String nombrePartida;
	private BigDecimal importePartida;
	private String descripcionPartida;

	public Partida() {
	}

	public Partida(Presupuesto presupuesto, String nombrePartida, BigDecimal importePartida,
			String descripcionPartida) {
		this.presupuesto = presupuesto;
		this.nombrePartida = nombrePartida;
		this.importePartida = importePartida;
		this.descripcionPartida = descripcionPartida;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_partida", unique = true, nullable = false)
	public Integer getIdPartida() {
		return this.idPartida;
	}

	public void setIdPartida(Integer idPartida) {
		this.idPartida = idPartida;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_presupuesto")
	public Presupuesto getPresupuesto() {
		return this.presupuesto;
	}

	public void setPresupuesto(Presupuesto presupuesto) {
		this.presupuesto = presupuesto;
	}

	@Column(name = "nombre_partida")
	public String getNombrePartida() {
		return this.nombrePartida;
	}

	public void setNombrePartida(String nombrePartida) {
		this.nombrePartida = nombrePartida;
	}

	@Column(name = "importe_partida", precision = 38)
	public BigDecimal getImportePartida() {
		return this.importePartida;
	}

	public void setImportePartida(BigDecimal importePartida) {
		this.importePartida = importePartida;
	}

	@Column(name = "descripcion_partida", length = 16777215)
	public String getDescripcionPartida() {
		return this.descripcionPartida;
	}

	public void setDescripcionPartida(String descripcionPartida) {
		this.descripcionPartida = descripcionPartida;
	}

	@Enumerated(EnumType.STRING)
	@Column(name = "estado_partida", length=20 )
	public EstadoPresupuestoEnum getEstadoPartida() {
		return estadoPartida;
	}

	public void setEstadoPartida(EstadoPresupuestoEnum estadoPartida) {
		this.estadoPartida = estadoPartida;
	}

}
