package org.servialtura.contabilidad.base.model;
// default package
// Generated 18-oct-2016 19:34:49 by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Partida generated by hbm2java
 */
@Entity
@Table(name = "PARTIDA", catalog = "SERVIALTURA")
public class Partida implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1450122648967981882L;
	private Integer idPartida;
	private Presupuesto presupuesto;
	private String nombrePartida;
	private String importePartida;
	private List<LineaPartida> lineasPartida = new ArrayList<LineaPartida>(0);

	public Partida() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_partida", unique = true, nullable = false)
	public Integer getIdPartida() {
		return this.idPartida;
	}

	public void setIdPartida(Integer idPartida) {
		this.idPartida = idPartida;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_presupuesto")
	public Presupuesto getPresupuesto() {
		return this.presupuesto;
	}

	public void setPresupuesto(Presupuesto presupuesto) {
		this.presupuesto = presupuesto;
	}

	@Column(name = "nombre_partida", length = 100)
	public String getNombrePartida() {
		return this.nombrePartida;
	}

	public void setNombrePartida(String nombrePartida) {
		this.nombrePartida = nombrePartida;
	}

	@Column(name = "importe_partida", length = 45)
	public String getImportePartida() {
		return this.importePartida;
	}

	public void setImportePartida(String importePartida) {
		this.importePartida = importePartida;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "partida")
	public List<LineaPartida> getLineasPartida() {
		return this.lineasPartida;
	}

	public void setLineasPartida(List<LineaPartida> lineaPartidas) {
		this.lineasPartida = lineaPartidas;
	}

}
