package org.servialtura.contabilidad.base.model;
// default package
// Generated 01-oct-2016 18:39:37 by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Presupuesto generated by hbm2java
 */
@Entity
@Table(name = "PRESUPUESTO", catalog = "SERVIALTURA")
public class Presupuesto implements java.io.Serializable {

	private static final long serialVersionUID = 4567239054460883494L;
	private Integer idPresupuesto;
	private String estadoPresupuesto;
	private Float importePresupuesto;
	private Solicitud solicitud;
	private Boolean tieneFacturaSuplidos;
	private List<Factura> facturas = new ArrayList<Factura>(0);
	private List<Partida> partidas = new ArrayList<Partida>(0);

	public Presupuesto() {
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idPresupuesto", unique = true, nullable = false)
	public Integer getIdPresupuesto() {
		return this.idPresupuesto;
	}

	public void setIdPresupuesto(Integer idPresupuesto) {
		this.idPresupuesto = idPresupuesto;
	}

	@Column(name = "estado_presupuesto", length = 20)
	public String getEstadoPresupuesto() {
		return this.estadoPresupuesto;
	}

	public void setEstadoPresupuesto(String estadoPresupuesto) {
		this.estadoPresupuesto = estadoPresupuesto;
	}

	@Column(name = "importe_presupuesto", precision = 12, scale = 0)
	public Float getImportePresupuesto() {
		return this.importePresupuesto;
	}

	public void setImportePresupuesto(Float importePresupuesto) {
		this.importePresupuesto = importePresupuesto;
	}


	@OneToMany(fetch = FetchType.LAZY, mappedBy = "presupuesto")
	public List<Factura> getFacturas() {
		return this.facturas;
	}

	public void setFacturas(List<Factura> facturas) {
		this.facturas = facturas;
	}


	@ManyToOne(fetch = FetchType.LAZY, cascade=CascadeType.ALL)
	@JoinColumn(name = "idSolicitud")
	public Solicitud getSolicitud() {
		return solicitud;
	}

	public void setSolicitud(Solicitud solicitud) {
		this.solicitud = solicitud;
	}



	@Column(name = "tiene_factura_suplidos")
	public Boolean getTieneFacturaSuplidos() {
		return tieneFacturaSuplidos;
	}

	public void setTieneFacturaSuplidos(Boolean tieneFacturaSuplidos) {
		this.tieneFacturaSuplidos = tieneFacturaSuplidos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "presupuesto")
	public List<Partida> getPartidas() {
		return partidas;
	}

	public void setPartidas(List<Partida> partidas) {
		this.partidas = partidas;
	}

}
