package org.servialtura.contabilidad.base.model;
// default package
// Generated 01-oct-2016 18:39:37 by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Rol generated by hbm2java
 */
@Entity
@Table(name = "ROL", catalog = "SERVIALTURA")
public class Rol implements java.io.Serializable {


	private static final long serialVersionUID = 208679702666918681L;
	private Integer idRol;
	private String nombreRol;

	public Rol() {
	}

	public Rol(String nombreRol) {
		this.nombreRol = nombreRol;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idRol", unique = true, nullable = false)
	public Integer getIdRol() {
		return this.idRol;
	}

	public void setIdRol(Integer idRol) {
		this.idRol = idRol;
	}

	@Column(name = "nombre_rol", length = 45)
	public String getNombreRol() {
		return this.nombreRol;
	}

	public void setNombreRol(String nombreRol) {
		this.nombreRol = nombreRol;
	}

}
