package org.servialtura.contabilidad.base.model;
// default package
// Generated 01-oct-2016 18:39:37 by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Solicitud generated by hbm2java
 */
@Entity
@Table(name = "SOLICITUD", catalog = "SERVIALTURA")
public class Solicitud implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5750909401148288570L;
	private Integer idSolicitud;
	private Date fechaSolicitud;
	private String descripcionSolicitud;
	private String emailContacto;
	private String telefonoContacto;
	private String nombreContacto;
	private List<Presupuesto> presupuestos;

	public Solicitud() {
	}

	public Solicitud(Date fechaSolicitud, String descripcionSolicitud, String emailContacto, String telefonoContacto) {
		this.fechaSolicitud = fechaSolicitud;
		this.descripcionSolicitud = descripcionSolicitud;
		this.emailContacto = emailContacto;
		this.telefonoContacto = telefonoContacto;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idSolicitud", unique = true, nullable = false)
	public Integer getIdSolicitud() {
		return this.idSolicitud;
	}

	public void setIdSolicitud(Integer idSolicitud) {
		this.idSolicitud = idSolicitud;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_solicitud", length = 19)
	public Date getFechaSolicitud() {
		return this.fechaSolicitud;
	}

	public void setFechaSolicitud(Date fechaSolicitud) {
		this.fechaSolicitud = fechaSolicitud;
	}

	@Column(name = "descripcion_solicitud", length = 65535)
	public String getDescripcionSolicitud() {
		return this.descripcionSolicitud;
	}

	public void setDescripcionSolicitud(String descripcionSolicitud) {
		this.descripcionSolicitud = descripcionSolicitud;
	}

	@Column(name = "email_contacto", length = 100)
	public String getEmailContacto() {
		return this.emailContacto;
	}

	public void setEmailContacto(String emailContacto) {
		this.emailContacto = emailContacto;
	}

	@Column(name = "telefono_contacto", length = 45)
	public String getTelefonoContacto() {
		return this.telefonoContacto;
	}

	public void setTelefonoContacto(String telefonoContacto) {
		this.telefonoContacto = telefonoContacto;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "solicitud")
	public List<Presupuesto> getPresupuestos() {
		return presupuestos;
	}

	public void setPresupuestos(List<Presupuesto> presupuestos) {
		this.presupuestos = presupuestos;
	}

	@Column(name = "nombre_contacto", length = 50)
	public String getNombreContacto() {
		return nombreContacto;
	}

	public void setNombreContacto(String nombreContacto) {
		this.nombreContacto = nombreContacto;
	}

}
