package org.servialtura.contabilidad.base.model;
// default package
// Generated 01-oct-2016 18:39:37 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Trabajo generated by hbm2java
 */
@Entity
@Table(name = "TRABAJO", catalog = "SERVIALTURA")
public class Trabajo implements java.io.Serializable {

	private Integer idTrabajo;
	private String descripcionTrabajo;
	private Float precioUnidad;

	public Trabajo() {
	}

	public Trabajo(String descripcionTrabajo, Float precioUnidad) {
		this.descripcionTrabajo = descripcionTrabajo;
		this.precioUnidad = precioUnidad;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idTrabajo", unique = true, nullable = false)
	public Integer getIdTrabajo() {
		return this.idTrabajo;
	}

	public void setIdTrabajo(Integer idTrabajo) {
		this.idTrabajo = idTrabajo;
	}

	@Column(name = "descripcion_trabajo", length = 100)
	public String getDescripcionTrabajo() {
		return this.descripcionTrabajo;
	}

	public void setDescripcionTrabajo(String descripcionTrabajo) {
		this.descripcionTrabajo = descripcionTrabajo;
	}

	@Column(name = "precio_unidad", precision = 12, scale = 0)
	public Float getPrecioUnidad() {
		return this.precioUnidad;
	}

	public void setPrecioUnidad(Float precioUnidad) {
		this.precioUnidad = precioUnidad;
	}

}
