package org.servialtura.contabilidad.base.model;
// default package
// Generated 18-dic-2016 18:36:13 by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UnidadMaterial generated by hbm2java
 */
@Entity
@Table(name = "UNIDAD_MATERIAL", catalog = "SERVIALTURA")
public class UnidadMaterial implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2256448112895046799L;
	private Integer idUnidadMaterial;
	private String nombreUnidad;
	private String descripcionUnidad;

	public UnidadMaterial() {
	}

	public UnidadMaterial(String nombreUnidad, String descripcionUnidad) {
		this.nombreUnidad = nombreUnidad;
		this.descripcionUnidad = descripcionUnidad;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idUnidadMaterial", unique = true, nullable = false)
	public Integer getIdUnidadMaterial() {
		return this.idUnidadMaterial;
	}

	public void setIdUnidadMaterial(Integer idUnidadMaterial) {
		this.idUnidadMaterial = idUnidadMaterial;
	}

	@Column(name = "nombreUnidad")
	public String getNombreUnidad() {
		return this.nombreUnidad;
	}

	public void setNombreUnidad(String nombreUnidad) {
		this.nombreUnidad = nombreUnidad;
	}

	@Column(name = "descripcionUnidad")
	public String getDescripcionUnidad() {
		return this.descripcionUnidad;
	}

	public void setDescripcionUnidad(String descripcionUnidad) {
		this.descripcionUnidad = descripcionUnidad;
	}

}
