package org.servialtura.contabilidad.base.model;
// default package
// Generated 18-dic-2016 18:36:13 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UnidadServicio generated by hbm2java
 */
@Entity
@Table(name = "UNIDAD_SERVICIO", catalog = "SERVIALTURA")
public class UnidadServicio implements java.io.Serializable {

	private Integer idUnidadServicio;
	private String nombreUnidad;
	private String descripcionUnidad;
	private Set<Servicio> servicios = new HashSet<Servicio>(0);

	public UnidadServicio() {
	}

	public UnidadServicio(String nombreUnidad, String descripcionUnidad, Set<Servicio> servicios) {
		this.nombreUnidad = nombreUnidad;
		this.descripcionUnidad = descripcionUnidad;
		this.servicios = servicios;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idUnidadServicio", unique = true, nullable = false)
	public Integer getIdUnidadServicio() {
		return this.idUnidadServicio;
	}

	public void setIdUnidadServicio(Integer idUnidadServicio) {
		this.idUnidadServicio = idUnidadServicio;
	}

	@Column(name = "nombreUnidad")
	public String getNombreUnidad() {
		return this.nombreUnidad;
	}

	public void setNombreUnidad(String nombreUnidad) {
		this.nombreUnidad = nombreUnidad;
	}

	@Column(name = "descripcionUnidad")
	public String getDescripcionUnidad() {
		return this.descripcionUnidad;
	}

	public void setDescripcionUnidad(String descripcionUnidad) {
		this.descripcionUnidad = descripcionUnidad;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "unidadServicio")
	public Set<Servicio> getServicios() {
		return this.servicios;
	}

	public void setServicios(Set<Servicio> servicios) {
		this.servicios = servicios;
	}

}
